"""RETIRED (24 Sep 2026): data/sfo_paint.* and data/sfo_pavement.* are now generated from USDA NAIP 2024 by
tools/imagery/paint_pave_naip.py. This script only re-creates the frame-migrated Google-screenshot polygons for
comparison, in the gitignored refs/cache/sat_legacy/ (sfo_paint.google.json, sfo_pavement.google.json).

Former generator for data/sfo_paint.{json,js} and data/sfo_pavement.{json,js} in the current world frame.

Why a separate generator: the green-paint and extra-pavement polygons were classified from the owner's Google Maps
screenshots by paint.py/paint_export.py and pavement.py/pave_classify.py/pave_export.py, in the LEGACY world frame
'equirect-v1' (tools/geo_frame.py). Their pixel intermediates (work/*.npy) are not kept, and the owner's rule since
24 Sep 2026 is that no committed coordinates may be derived from the screenshots any more. So the published polygons
of 23 Sep 2026 (commit 306cb11, frozen byte-identical in tools/sat/legacy/*.equirect-v1.json) are the source here and
every vertex is mapped exactly into the current frame: geo_frame.legacy_to_world (legacy inverse -> NAD83(2011)
lat/lon -> GRS80 local tangent plane). Straight edges between vertices stay straight to < 1 mm (the mapping's
non-linear part is < 0.13 m per 100 m, docs/research/imagery.md s.4.4). Values keep the source's 0.1 m rounding.

    python3 tools/sat/legacy_export.py        # writes refs/cache/sat_legacy/sfo_{paint,pavement}.google.*
"""
import json, math, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.join(HERE, '..', '..')
sys.path.insert(0, os.path.join(HERE, '..'))
import geo_frame as GF

JOBS = [('paint', 'PAINT', 'paint_export.py'), ('pavement', 'PAVEMENT', 'pave_export.py')]


def conv_ring(ring, stats):
    out = []
    for x, z in ring:
        X, Z = GF.legacy_to_world(x, z); stats.append(math.hypot(X - x, Z - z))
        out.append([round(X, 1), round(Z, 1)])
    return out


def main():
    for name, var, gen in JOBS:
        src = os.path.join(ROOT, 'refs', 'cache', 'sat_legacy', f'sfo_{name}.equirect-v1.json')
        d = json.load(open(src)); stats = []
        res = dict(d)
        res['polys'] = [[conv_ring(r, stats) for r in poly] for poly in d['polys']]
        res['frame'] = GF.FRAME_ID
        res['provenance'] = (f'tools/sat/{gen} (legacy frame equirect-v1, 23 Sep 2026) -> tools/sat/legacy_export.py '
                             '(exact mapping into the current frame, 24 Sep 2026)')
        blob = json.dumps(res, separators=(',', ':'))
        open(os.path.join(ROOT, 'refs', 'cache', 'sat_legacy', f'sfo_{name}.google.json'), 'w').write(blob)
        open(os.path.join(ROOT, 'refs', 'cache', 'sat_legacy', f'sfo_{name}.google.js'), 'w').write(
            f'// generated by tools/sat/legacy_export.py from tools/sat/legacy/sfo_{name}.equirect-v1.json '
            f'(tools/sat/{gen}, legacy frame)\nexport const {var} = ' + blob + ';\n')
        stats.sort()
        print(f'{name}: {len(res["polys"])} polygons, {len(stats)} vertices moved: median {stats[len(stats) // 2]:.2f} m,'
              f' max {stats[-1]:.2f} m')


if __name__ == '__main__':
    main()
