"""Export from the screenshot pipeline (needs the work/*.npy intermediates). NOT the generator of the committed
data any more: the owner ruled (24 Sep 2026) that no committed coordinates may be derived from the Google
screenshots; data/sfo_paint.* and data/sfo_pavement.* are generated from USDA NAIP 2024 by
tools/imagery/paint_pave_naip.py. This script now writes only to the gitignored refs/cache/sat_legacy/. If re-run, everything (sim_of, stview grid) is in the
current world frame (tools/geo_frame.py)."""
import json, os
import numpy as np, cv2
from scipy import ndimage as ndi
from common import *
from paint import W, H, RES, S0, T1
from stview import w2st, st2w
m = np.load(SP + 'paint_mask.npy')
def P(pts): return np.array([[(s - S0) / RES, (T1 - t) / RES] for s, t in pts])
pav = np.zeros((H, W), np.uint8); bld = np.zeros((H, W), np.uint8)
for k in ('taxiways', 'runways'):
    for ring in rings_all(k): cv2.fillPoly(pav, [np.round(P([w2st(*q) for q in ring]) * 4).astype(np.int32)], 1, shift=2)
for k in ('complex', 'ba', 'structures'):
    for ring in rings_all(k): cv2.fillPoly(bld, [np.round(P([w2st(*q) for q in ring]) * 4).astype(np.int32)], 1, shift=2)
near = ndi.distance_transform_edt(pav == 0) * RES < 28
mk = m & near & (bld == 0)
mk = ndi.binary_closing(mk, iterations=2); mk = ndi.binary_opening(mk, iterations=1)
lab, nl = ndi.label(mk); sizes = ndi.sum(mk, lab, range(1, nl + 1))
keep = np.isin(lab, 1 + np.nonzero(sizes * RES * RES >= 40)[0])
mk = keep & ~(pav > 0)  # the paint is on the island pavement next to the taxiway, not on the taxiway itself
cs, hier = cv2.findContours(mk.astype(np.uint8), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
polys = []
for i, c in enumerate(cs):
    if hier[0][i][3] != -1 or cv2.contourArea(c) * RES * RES < 30: continue
    rings = [c]; k = hier[0][i][2]
    while k != -1:
        if cv2.contourArea(cs[k]) * RES * RES > 20: rings.append(cs[k])
        k = hier[0][k][0]
    out = []
    for r in rings:
        a = cv2.approxPolyDP(r, 0.7 / RES, True)[:, 0, :].astype(np.float64)
        pts = [st2w(S0 + (p[0] + 0.5) * RES, T1 - (p[1] + 0.5) * RES) for p in a]
        out.append([[round(x, 1), round(z, 1)] for x, z in pts])
    polys.append(out)
area = mk.sum() * RES * RES
res = {'frame': GF.FRAME_ID, 'note': 'Green no-taxi island paint (FAA AC 150/5340-1M para 1.5.2) mapped from georeferenced satellite screenshots (reference only).', 'polys': polys}
json.dump(res, open(os.path.join(LEGACY, 'sfo_paint.google.json'), 'w'), separators=(',', ':'))
open(os.path.join(LEGACY, 'sfo_paint.google.js'), 'w').write('// generated by tools/sat/paint_export.py\nexport const PAINT = ' + json.dumps(res, separators=(',', ':')) + ';\n')
print(len(polys), 'polygons', round(area), 'm2', os.path.getsize(os.path.join(LEGACY, 'sfo_paint.google.json')), 'bytes')
vis = np.zeros((H, W, 3), np.uint8); vis[pav > 0] = (90, 90, 90); vis[bld > 0] = (40, 40, 120); vis[mk] = (60, 220, 120)
cv2.imwrite(SP + 'paint_clean.jpg', cv2.resize(vis, None, fx=0.35, fy=0.35, interpolation=cv2.INTER_AREA))
