"""Export from the screenshot pipeline (needs the work/*.npy intermediates). NOT the generator of the committed
data any more: the owner ruled (24 Sep 2026) that no committed coordinates may be derived from the Google
screenshots; data/sfo_paint.* and data/sfo_pavement.* are generated from USDA NAIP 2024 by
tools/imagery/paint_pave_naip.py. This script now writes only to the gitignored refs/cache/sat_legacy/. If re-run, everything (sim_of, stview grid) is in the
current world frame (tools/geo_frame.py)."""
import json, os
import numpy as np, cv2
from scipy import ndimage as ndi
from common import *
from pavement import W, H, RES, S0, T1, P
from stview import w2st, st2w
img = np.load(SP + 'apt_mosaic.npy'); best = np.load(SP + 'apt_best.npy'); lab = np.load(SP + 'pave_add_lab.npy')
info = json.load(open(LSP + 'pave_add.json'))
b, g, r = [img[..., i].astype(np.int16) for i in range(3)]
lum = (r + g + b) / 3
water = (b > r + 4) & (g > r + 2) & (lum < 125) & (best > 0)
water = ndi.binary_opening(water, iterations=2)
lab_w, nw = ndi.label(water); ws = ndi.sum(water, lab_w, range(1, nw + 1))
water = np.isin(lab_w, 1 + np.nonzero(ws * RES * RES > 5000)[0])      # only large water bodies
water = ndi.binary_dilation(water, iterations=10)
EXCLUDE = {17}  # island interior mis-classified (soil)
keep_ids = [i for k, i in enumerate(info['big']) if k not in EXCLUDE]
add = np.isin(lab, keep_ids) & ~water
add = ndi.binary_closing(add, iterations=2); add = ndi.binary_opening(add, iterations=2)
# fill holes (unmapped roofs, parked aircraft, vehicles, shadows) up to 8000 m2 and smooth the outline (sigma 2.5 m)
holes = ndi.binary_fill_holes(add) & ~add
lh, nh = ndi.label(holes); hsz = ndi.sum(holes, lh, range(1, nh + 1))
add |= np.isin(lh, 1 + np.nonzero(hsz * RES * RES < 8000)[0])
add = ndi.gaussian_filter(add.astype(np.float32), 2.5 / RES) > 0.5
lab2, n2 = ndi.label(add); s2 = ndi.sum(add, lab2, range(1, n2 + 1))
add = np.isin(lab2, 1 + np.nonzero(s2 * RES * RES > 1500)[0])
cs, hier = cv2.findContours(add.astype(np.uint8), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
polys = []
for i, c in enumerate(cs):
    if hier[0][i][3] != -1 or cv2.contourArea(c) * RES * RES < 1500: continue
    rings = [c]; k = hier[0][i][2]
    while k != -1:
        if cv2.contourArea(cs[k]) * RES * RES > 400: rings.append(cs[k])
        k = hier[0][k][0]
    out = []
    for rr in rings:
        a = cv2.approxPolyDP(rr, 1.0 / RES, True)[:, 0, :].astype(np.float64)
        out.append([[round(x, 1), round(z, 1)] for x, z in (st2w(S0 + (p[0] + 0.5) * RES, T1 - (p[1] + 0.5) * RES) for p in a)])
    polys.append(out)
area = add.sum() * RES * RES
res = {'frame': GF.FRAME_ID, 'note': 'Paved areas not in the SFO Museum geometry (cargo/maintenance aprons, service roads, shoulders), classified from georeferenced satellite screenshots (reference only).', 'polys': polys}
json.dump(res, open(os.path.join(LEGACY, 'sfo_pavement.google.json'), 'w'), separators=(',', ':'))
open(os.path.join(LEGACY, 'sfo_pavement.google.js'), 'w').write('// generated by tools/sat/pave_export.py\nexport const PAVEMENT = ' + json.dumps(res, separators=(',', ':')) + ';\n')
print(len(polys), 'polys', round(area / 1e4, 1), 'ha', os.path.getsize(os.path.join(LEGACY, 'sfo_pavement.google.json')), 'bytes')
vis = img.copy() // 2; vis[add] = (vis[add] * 0.3 + np.array([40, 200, 255]) * 0.7).astype(np.uint8); vis[water & (best > 0)] = (vis[water & (best > 0)] * 0.5 + np.array([200, 60, 0]) * 0.5).astype(np.uint8)
cv2.imwrite(SP + 'pave_final.jpg', cv2.resize(vis, None, fx=0.3, fy=0.3, interpolation=cv2.INTER_AREA))
