#!/usr/bin/env python3
"""Write data/brands.js: which brand (livery) an aircraft wears, for js/live/lookup.js.

Inputs
  tools/models/out/regional_brands.json  registration -> marketing network of US regional airframes (US DOT BTS
                                         Marketing Carrier On-Time Performance, 2026-05..07, public domain; observed)
                                         and registration series rules derived from it (inferred)
  tools/liveries/brands_meta.py          brand codes, names, callsigns, regional operators, SFO majority, overrides
  tools/liveries/liveries.py             painted liveries (runtime colours for the procedural airframe / fallback)
Output (ES module, generated - do not edit)
  BRAND_INFO      code -> {name, livery (version text) | null, colors (runtime sRGB family) | null, refs}
  CALLSIGN_BRAND  ICAO airline designator -> brand of its mainline flights
  REGIONAL_OPS    regional callsign -> BTS operator code;  NETWORK_BRAND  BTS network -> brand
  REG_BRAND       brand -> space-separated registrations (observed: BTS tail table, SkyWest + Horizon, the regional
                  operators that fly to SFO; 586 tails)
  REG_SERIES      [operator, BTS type, digits, suffix, first number, last number, brand] (inferred; n >= 5, E-Jet / CRJ200)
  OP_MAJORITY     operator -> type -> brand (SkyWest / Horizon: SFO landings; others: BTS flights; inferred)
  REG_OVERRIDE    registration -> {brand, special, src, rendered}
Usage: python3 tools/liveries/build_brands_js.py
"""
import collections, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common
from brands_meta import BRANDS, REGIONAL_OPS, NETWORK_BRAND, SFO_MAJORITY, REG_OVERRIDE

SRC = os.path.join(common.ROOT, 'tools', 'models', 'out', 'regional_brands.json')
OUT = os.path.join(common.ROOT, 'data', 'brands.js')


def main():
    import liveries
    rb = json.load(open(SRC))
    ops_at_sfo = {'OO', 'QX'}          # regional operators with SFO flights in BTS 2026-05..07 (liveries.md §1.1, §2)
    reg = collections.defaultdict(list)
    for tail, t in rb['tails'].items():
        if t['op'] in ops_at_sfo or t.get('sfo', 0) > 0:
            reg[NETWORK_BRAND.get(t['brand'], t['brand'])].append(tail)
    series = []
    for r in rb['series']:
        if r['operator'] not in ops_at_sfo or r['n'] < 5 or r['type'] not in ('E175', 'E170', 'CRJ2'): continue
        m1 = re.match(r'N(\d+)([A-Z]*)$', r['first']); m2 = re.match(r'N(\d+)([A-Z]*)$', r['last'])
        series.append([r['operator'], r['type'], len(m1.group(1)), m1.group(2), int(m1.group(1)), int(m2.group(1)), NETWORK_BRAND[r['brand']]])
    maj = collections.defaultdict(collections.Counter)
    for t in rb['tails'].values(): maj[(t['op'], t.get('type', ''))][t['brand']] += t['n']
    op_major = {}
    for (op, typ), c in maj.items():
        op_major.setdefault(op, {})[typ] = NETWORK_BRAND[c.most_common(1)[0][0]]
    for op, m in SFO_MAJORITY.items(): op_major.setdefault(op, {}).update(m)
    for op, m in op_major.items():
        if '*' not in m: m['*'] = collections.Counter(m.values()).most_common(1)[0][0]
    info = {}
    for code, (name, cs) in BRANDS.items():
        L = liveries.LIVERIES.get(code)
        info[code] = dict(name=name, livery=L['version'] if L else None, colors=L.get('runtime') if L else None,
                          refs=L['refs'][:2] if L else None)
    callsign = {c: code for code, (_, cs) in BRANDS.items() for c in cs}
    js = ['// Generated by tools/liveries/build_brands_js.py - do not edit. Which brand (livery) an aircraft wears: see the',
          '// header of that script and docs/research/liveries_impl.md. REG_BRAND is observed (US DOT BTS marketing-carrier',
          f"// data, months {', '.join(rb['months'])}, public domain); REG_SERIES and OP_MAJORITY are inferred from it.",
          'export const BRAND_INFO = ' + json.dumps(info, ensure_ascii=False, separators=(',', ':')) + ';',
          'export const CALLSIGN_BRAND = ' + json.dumps(callsign, separators=(',', ':')) + ';',
          'export const REGIONAL_OPS = ' + json.dumps(REGIONAL_OPS, separators=(',', ':')) + ';',
          'export const NETWORK_BRAND = ' + json.dumps(NETWORK_BRAND, separators=(',', ':')) + ';',
          'export const REG_BRAND = ' + json.dumps({b: ' '.join(sorted(v)) for b, v in sorted(reg.items())}, separators=(',', ':')) + ';',
          'export const REG_SERIES = ' + json.dumps(series, separators=(',', ':')) + ';',
          'export const OP_MAJORITY = ' + json.dumps(op_major, separators=(',', ':')) + ';',
          'export const REG_OVERRIDE = ' + json.dumps(REG_OVERRIDE, ensure_ascii=False, separators=(',', ':')) + ';',
          'export const BRAND_SOURCE = ' + json.dumps(dict(tails=rb['source'], months=rb['months']), separators=(',', ':')) + ';', '']
    open(OUT, 'w').write('\n'.join(js))
    print(f"{os.path.relpath(OUT, common.ROOT)}: {sum(len(v) for v in reg.values())} tails, {len(series)} series, {len(info)} brands, "
          f"{os.path.getsize(OUT) / 1024:.1f} KB")


if __name__ == '__main__':
    main()
