// Interior tour: named stops in the flight deck and cabin, smooth camera flights between them, and a first-person
// camera while inside (drag to look, keys / wheel / pinch / on-screen arrows to walk), held inside the walkable volume
// of web/viewer/tour_data.js (generated by web/tour_data.py from the interior tables of model/interior.py).
//
// Coordinates: tour_data is in MODEL axes (x = STA aft, y = BL starboard, z = WL up); the scene is glTF
// (X = y, Y = z, Z = x).  The first-person pose is p (model, the eye point), yaw (heading in the x-y plane: 0 = aft,
// pi = forward) and pitch (up +).  The OrbitControls are switched off while inside; the camera looks at a point 0.3 m
// ahead, so the stage's near plane follows to 1 cm.
import * as THREE from 'three';
import { TOUR } from './tour_data.js';

export { TOUR };
const D2R = Math.PI / 180;
const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const smooth = (t) => t * t * (3 - 2 * t);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);
const wrap = (a) => Math.atan2(Math.sin(a), Math.cos(a));
const lerpAngle = (a, b, t) => a + wrap(b - a) * t;
export const toGL = (p) => new THREE.Vector3(p[1], p[2], p[0]);
export const toModel = (v) => [v.z, v.x, v.y];
const RM = window.matchMedia ? matchMedia('(prefers-reduced-motion: reduce)') : null;

// walking (m/s, rad/s), look sensitivity, limits
const SPEED = { walk: 1.0, run: 2.0, lift: 0.5, turn: 95 * D2R, pitch: 70 * D2R, accel: 10 };
const PITCH_MAX = 80 * D2R;
const WHEEL_M = 0.0022;                 // m per wheel pixel (a 100 px notch = 0.22 m)
const PINCH_M = 0.006;                  // m per pixel of pinch spread / two-finger drag
const FOV_MAX = 95, H_FOV_MIN = 70;    // widen the vertical FOV until at least 70 deg show across
// portrait phones (aspect < PORTRAIT): the vertical FOV capped lower and the optical axis (~ the horizon) put
// PORTRAIT_AXIS of the way down the view instead of half way (Stage.setViewShift, an off-axis window: verticals stay
// vertical) -- review r1 NAV1-03: at FOV_MAX the top ~40 % of every cabin view was flat headliner
const PORTRAIT = 0.8, FOV_MAX_PORTRAIT = 85, PORTRAIT_AXIS = 0.4;
const SIDESTEP_PULL = 0.5;              // m: a blocked sidestep in the aisle slides toward a seat this close (NAV1-07)
const SEAT_TURN = 0.4;                  // s: a walk into a seat turns the view to the seat's facing (NAV2-03) ...
const SEAT_PITCH = -8 * D2R;            // ... and this pitch (a seat region's own `pitch`: the crew seats take their stop's,
//                                          review r4 NAV8-03: at -8 the walked-in crew seat saw half sky, the PFD cut off)
const STANDING = new Set(['aisle', 'crew_gap', 'flight_deck', 'vestibule', 'vestibule_door']);
// a walk from a stop's steep look (pilot -21, airstair -48 deg) levels the view to WALK_PITCH over ~LEVEL_TIME while
// it moves in one of these regions (review r3 NAV3-03: walking on, the carpet filled the view); any look input (R / F,
// a drag) keeps the user's own pitch
const LEVELING = new Set([...STANDING, 'doorway']);
const WALK_PITCH = -6 * D2R, LEVEL_TIME = 0.5;
const regionById = (id) => TOUR.regions.find((g) => g.id === id) || null;
const HINT_FADE = 2.5;                  // s after the first look / walk input inside, the controls hint fades
const ZW = 0.1;                         // height weight of the walk projection (project)
const RISE = 0.6;                       // m/s: the eye coming back up to the kept height (standing up, a ceiling passed)
const SINK = 0.6;                       // m/s: ... and down to a lower kept height (into the gap between the crew seats)

export function stopById(id) { return TOUR.stops.find((s) => s.id === id) || null; }
// where the eye is, for the stop button once walked away from a stop (review r4 NAV8-04)
const REGION_LABEL = { seat_pilot: 'Pilot seat', seat_copilot: 'Co-pilot seat', crew_gap: 'Flight deck',
  flight_deck: 'Flight deck', aisle: 'Cabin aisle', vestibule: 'Cabin entry', vestibule_door: 'Cabin entry',
  doorway: 'Airstair door' };
export function regionLabel(id) {
  if (!id) return null;
  if (REGION_LABEL[id]) return REGION_LABEL[id];
  const m = /^seat_pax(\d+)$/.exec(id);
  return m ? `PAX ${m[1]} seat` : null;
}
function angles(eye, target) {
  const dx = target[0] - eye[0], dy = target[1] - eye[1], dz = target[2] - eye[2];
  return { yaw: Math.atan2(dy, dx), pitch: Math.atan2(dz, Math.hypot(dx, dy)) };
}

// ---------------------------------------------------------------- walkable volume (the same rule as web/tour_data.py)
export function ceilingAt(x, a) {
  const C = TOUR.ceiling;
  const fx = clamp((x - C.x0) / C.dx, 0, C.nx - 1.000001), fa = clamp(a / C.da, 0, C.na - 1.000001);
  const i = fx | 0, j = fa | 0, u = fx - i, v = fa - j, z = C.z;
  return (z[i][j] * (1 - v) + z[i][j + 1] * v) * (1 - u) + (z[i + 1][j] * (1 - v) + z[i + 1][j + 1] * v) * u;
}
// nearest point of the union of the active regions: {p, d, region}.  zw < 1 weighs height differences less: a walk
// goes on under a lower ceiling (soffit, side lining, flight deck) or into a seat, the eye dipping to fit, instead of
// stopping at the edge; a region's own zw (crew_gap: 1) overrides it (a standing walker does not dip into it)
export function project(p, doors = {}, zw = 1) {
  let best = null, bd = Infinity, who = null, bt = 0;
  for (const R of TOUR.regions) {
    if (R.when && !(doors[R.when] >= 0.999)) continue;
    const x = clamp(p[0], R.x[0], R.x[1]), y = clamp(p[1], R.y[0], R.y[1]);
    let zhi = R.z[1];
    if (R.ceil) zhi = Math.min(zhi, ceilingAt(x, Math.abs(y)));
    if (zhi < R.z[0]) continue;
    const z = clamp(p[2], R.z[0], zhi);
    const w = R.zw != null ? Math.max(zw, R.zw) : zw;
    const d = (x - p[0]) ** 2 + (y - p[1]) ** 2 + (w * (z - p[2])) ** 2;
    if (d < bd) { bd = d; best = [x, y, z]; who = R.id; bt = (x - p[0]) ** 2 + (y - p[1]) ** 2 + (z - p[2]) ** 2; }
  }
  return { p: best || p.slice(), d: Math.sqrt(bt), region: who };
}

export class Tour {
  // stage: scene.js Stage; kin: Kinematics (door targets for the doorway region); hooks: {enter(stop), exit(to),
  // changed()} from main.js (state save / restore, UI sync)
  constructor({ stage, kin, hooks }) {
    this.stage = stage;
    this.kin = kin;
    this.hooks = hooks;
    this.active = false;            // the tour owns the camera (from the start of the flight in to the end of exit)
    this.inside = false;            // the camera is inside (after the fade into the cabin): lit as the cabin
    this.stop = null;               // the stop the camera is at / flying to (null once walked away)
    this.lastStop = null;           // for prev / next and the stop button
    this.p = TOUR.stops[0].eye.slice();
    this.zWant = this.p[2];         // the eye height the walker keeps (Q / E, a stop's eye); ceilings push it down
    this.region = null;
    this.yaw = 0; this.pitch = 0; this.fovBase = 70; this.fovKick = 0;
    this.tasks = [];                // the flight / fade sequence (update)
    this.keys = new Set();
    this.pad = { f: 0, s: 0, u: 0 };
    this.vel = [0, 0, 0];           // forward, right, up (m/s), smoothed
    this.turnVel = 0;
    this.pending = 0;               // wheel / pinch travel still to cover (m, forward)
    this.latch = null;              // a sideways step out of a seat held on the aisle / gap centre line until the strafe
    //                                 is released ({dir: +-1 of the strafe, y: the line}; NAV2-02)
    this.seatTurn = null;           // the turn to a seat's facing after a walk into it (NAV2-03)
    this.pitchAuto = false;         // the pitch is a stop's (not the user's): a walk levels it (NAV3-03)
    this.seatFlip = false;          // the walk into this seat turned the view round (> 90 deg): strafes reversed (NAV3-05)
    this.onInput = null;            // TourUI: the first walk / look input (the hint fades)
    this.pointers = new Map();
    this.fade = document.getElementById('tourFade');
    this.motionOverride = null;     // tests: force flights on (true) / off (false) regardless of reduced motion
    this._wirePointer(stage.renderer.domElement);
  }

  get motion() { return this.motionOverride != null ? this.motionOverride : !(RM && RM.matches); }
  get flying() { return this.tasks.length > 0; }
  doors() { const t = this.kin.t; return { door_airstair: t.door_airstair, door_cargo: t.door_cargo }; }

  // ---------------------------------------------------------------- camera
  dir() {
    const cp = Math.cos(this.pitch);
    return [cp * Math.cos(this.yaw), cp * Math.sin(this.yaw), Math.sin(this.pitch)];
  }
  get portrait() { const v = this.stage.size; return v.w / Math.max(1, v.h) < PORTRAIT; }
  fovFor(base) {
    const asp = Math.max(0.2, this.stage.camera.aspect);
    const need = 2 * Math.atan(Math.tan(H_FOV_MIN * D2R / 2) / asp) / D2R;
    return clamp(Math.max(base, need), 20, this.portrait ? FOV_MAX_PORTRAIT : FOV_MAX);
  }
  apply() {
    const cam = this.stage.camera, c = this.stage.controls, d = this.dir();
    cam.position.copy(toGL(this.p));
    c.target.copy(toGL([this.p[0] + 0.3 * d[0], this.p[1] + 0.3 * d[1], this.p[2] + 0.3 * d[2]]));
    cam.lookAt(c.target);
    const fov = this.fovFor(this.fovBase) + this.fovKick;
    if (Math.abs(cam.fov - fov) > 1e-3) { cam.fov = fov; cam.updateProjectionMatrix(); }
    this.stage.setViewShift(this.inside && this.portrait ? 0.5 - PORTRAIT_AXIS : 0);
    this._aspect = cam.aspect;
    this.stage.needsRender = true;
  }
  // a stop's heading / pitch (a portrait screen may take its own pitch and heading: the airstair, NAV3-02 / NAV8-05)
  stopAngles(s) {
    const a = angles(s.eye, s.target);
    if (s.pitch_portrait != null && this.portrait) a.pitch = s.pitch_portrait * D2R;
    if (s.yaw_portrait != null && this.portrait) a.yaw = s.yaw_portrait * D2R;
    return a;
  }
  setPose(stop) {
    const s = typeof stop === 'string' ? stopById(stop) : stop;
    const a = this.stopAngles(s);
    this.p = s.eye.slice();
    this.zWant = s.eye[2];
    this.region = project(this.p, this.doors()).region;
    this.yaw = a.yaw; this.pitch = a.pitch; this.fovBase = s.fov;
    this.latch = null; this.seatTurn = null; this.seatFlip = false;
    this.pitchAuto = true;
  }
  _setFade(o) {
    if (!this.fade) return;
    this.fade.style.opacity = String(clamp(o, 0, 1));
    this.fade.hidden = o <= 0.001;
  }

  // ---------------------------------------------------------------- enter / go / exit
  // Outside -> a stop: the exterior leg to the stop's approach pose (round the fuselage, not through it), a fade, the
  // cut inside, the fade back with a slight field-of-view settle.  Reduced motion: a cut.
  enter(id, { motion = this.motion } = {}) {
    const s = stopById(id) || TOUR.stops[0];
    if (this.active) { this.go(s.id, { motion }); return; }
    this.tasks = [];
    const st = this.stage, cam = st.camera, c = st.controls;
    st.tween = null;
    st.preset = null;
    c.enableDamping = false; c.update(); c.enableDamping = true;
    c.enabled = false;
    this.active = true;
    this.stop = s.id;
    this.lastStop = s.id;
    this.hooks.enter(s, motion);               // saves the exterior state, sets the scene up (doors, cutaway off ...)
    const cut = () => { this.inside = true; this.setPose(s); this.vel = [0, 0, 0]; this.pending = 0; this.apply(); };
    if (!motion) { cut(); this._setFade(0); this.hooks.changed(); return; }
    const A = TOUR.approach[s.approach] || TOUR.approach.door;
    const p0 = cam.position.clone(), t0 = c.target.clone(), f0 = cam.fov;
    const p1 = toGL(A.eye), t1 = toGL(A.target);
    const yc = 1.86;                                       // fuselage axis height (glTF Y), for the orbit round it
    const cyl = (v) => ({ th: Math.atan2(v.y - yc, v.x), r: Math.hypot(v.x, v.y - yc), z: v.z });
    const c0 = cyl(p0), c1 = cyl(p1);
    const dist = p0.distanceTo(p1);
    this.tasks.push({
      dur: clamp(0.6 + dist / 14, 0.9, 1.8),
      run: (f) => {
        const e = ease(f);
        const th = lerpAngle(c0.th, c1.th, e), r = c0.r + (c1.r - c0.r) * e, z = c0.z + (c1.z - c0.z) * e;
        cam.position.set(r * Math.cos(th), yc + r * Math.sin(th), z);
        c.target.lerpVectors(t0, t1, e);
        cam.lookAt(c.target);
        cam.fov = f0 + (s.fov - f0) * e;
        cam.updateProjectionMatrix();
        this._setFade(smooth(clamp((f - 0.62) / 0.38, 0, 1)));
      },
    });
    this.tasks.push({ dur: 0, run: () => { cut(); this.fovKick = 9; this.apply(); this._setFade(1); } });
    this.tasks.push({
      dur: 0.55,
      run: (f) => { this._setFade(1 - smooth(f)); this.fovKick = 9 * (1 - ease(f)); this.apply(); },
    });
    this.hooks.changed();
  }

  // inside -> a stop: a flight along stop -> via -> aisle -> via -> stop (Catmull-Rom, arc length), looking where
  // it goes in the middle of a long flight
  go(id, { motion = this.motion } = {}) {
    const s = stopById(id);
    if (!s) return;
    // a running flight completes first -- and so does a pending exit (a stop key / menu pick / prev / next during the
    // exit fade): the tour is then outside and goes back in from there (review r2 NAV2-01: the flight had been
    // pushed on the inactive tour, leaving the camera inside under the exterior UI with the orbit controls on)
    this.finish();
    if (!this.active) { this.enter(id, { motion }); return; }
    this.stop = s.id;
    this.lastStop = s.id;
    if (s.doors) for (const k in s.doors) this.hooks.door(k, s.doors[k], motion);
    if (!motion) { this.setPose(s); this.apply(); this.hooks.changed(); return; }
    const pts = [this.p.slice()];
    const here = project(this.p, this.doors());
    if (Math.abs(this.p[1]) > TOUR.aisle_band + 1e-3) {
      const y = Math.sign(this.p[1]) * (TOUR.aisle_band - 0.01);
      if (here.region === 'doorway') pts.push([this.p[0], -0.33, this.p[2]]);
      pts.push(project([this.p[0], y, Math.max(this.p[2], TOUR.crouch_min + 0.1)], this.doors()).p);
    }
    for (const v of s.via.slice().reverse()) pts.push(v);
    pts.push(s.eye);
    const V = [];
    for (const q of pts) {
      const v = new THREE.Vector3(q[0], q[1], q[2]);
      if (!V.length || V[V.length - 1].distanceTo(v) > 0.02) V.push(v);
    }
    const a0 = { yaw: this.yaw, pitch: this.pitch }, a1 = this.stopAngles(s);
    const fov0 = this.fovBase;
    if (V.length < 2) { this.setPose(s); this.apply(); this.hooks.changed(); return; }
    const curve = new THREE.CatmullRomCurve3(V, false, 'centripetal');
    const len = curve.getLength();
    // looking where it goes in the middle of a long flight, only when both ends look roughly that way (the main
    // heading, start -> end): a stop behind the camera is reached backing up, not by turning round twice
    const main = Math.atan2(V[V.length - 1].y - V[0].y, V[V.length - 1].x - V[0].x);
    const along = (yw) => smooth(clamp((Math.cos(wrap(yw - main)) - 0.2) / 0.6, 0, 1));
    const look = len > 1.2 && Math.hypot(V[V.length - 1].x - V[0].x, V[V.length - 1].y - V[0].y) > 1.0
      ? 0.85 * Math.min(along(a0.yaw), along(a1.yaw)) : 0;
    this.tasks.push({
      dur: clamp(0.55 + len / 1.6, 0.8, 3.4),
      run: (f) => {
        const e = ease(f);
        const q = curve.getPointAt(e);
        this.p = [q.x, q.y, q.z];
        const b = smooth(clamp((f - 0.12) / 0.76, 0, 1));
        let yaw = lerpAngle(a0.yaw, a1.yaw, b), pitch = a0.pitch + (a1.pitch - a0.pitch) * b;
        if (look) {
          // the overall heading, not the local tangent: the sideways steps into / out of a seat do not swing the view
          const wt = look * smooth(clamp(f / 0.3, 0, 1)) * smooth(clamp((1 - f) / 0.3, 0, 1));
          yaw = lerpAngle(yaw, main, wt);
          pitch += (-6 * D2R - pitch) * wt;
        }
        this.yaw = yaw; this.pitch = pitch;
        this.fovBase = fov0 + (s.fov - fov0) * b;
        this.apply();
      },
    });
    this.tasks.push({ dur: 0, run: () => { this.setPose(s); this.apply(); } });
    this.hooks.changed();
  }

  // inside -> outside: fade, the exterior view and state restored (main.js), fade back.  to: a camera preset name
  exit({ motion = this.motion, to = 'three_quarter' } = {}) {
    if (!this.active) return;
    this.tasks = [];
    this.keys.clear(); this.pad = { f: 0, s: 0, u: 0 }; this.vel = [0, 0, 0]; this.turnVel = 0; this.pending = 0;
    this.latch = null; this.seatTurn = null; this.seatFlip = false;
    const out = () => {
      this.active = false;
      this.inside = false;
      this.stop = null;
      this.fovKick = 0;
      this.stage.setViewShift(0);
      this.stage.controls.enabled = true;
      this.hooks.exit(to);
    };
    if (!motion) { out(); this._setFade(0); this.hooks.changed(); return; }
    this.tasks.push({ dur: 0.28, run: (f) => this._setFade(smooth(f)) });
    this.tasks.push({ dur: 0, run: () => { out(); this._setFade(1); this.hooks.changed(); } });
    this.tasks.push({ dur: 0.45, run: (f) => this._setFade(1 - smooth(f)) });
    this.hooks.changed();
  }

  // complete a running flight / fade at once (tests, or a new command mid-flight)
  finish() {
    let guard = 0;
    while (this.tasks.length && guard++ < 20) {
      const k = this.tasks.shift();
      k.run(1);
    }
    this._setFade(0);
  }

  next(step = 1) {
    const n = TOUR.stops.length;
    const i = Math.max(0, TOUR.stops.findIndex((s) => s.id === this.lastStop));
    this.go(TOUR.stops[(i + step + n) % n].id);
  }

  // ---------------------------------------------------------------- per frame
  update(dt) {
    let changed = false;
    if (this.tasks.length) {
      let left = dt;
      while (this.tasks.length) {
        const k = this.tasks[0];
        k.t = (k.t || 0) + left;
        const f = k.dur > 0 ? Math.min(1, k.t / k.dur) : 1;
        k.run(f);
        changed = true;
        if (f < 1) break;
        left = k.dur > 0 ? k.t - k.dur : left;
        this.tasks.shift();
        if (!this.tasks.length) this.hooks.changed();
      }
      if (this.tasks.length) return true;
    }
    if (!this.active) return changed;
    if (this.step(dt)) changed = true;
    if (this.inside) {
      // the viewport changed shape (panel, rotation): the field of view follows
      if (this.stage.camera.aspect !== this._aspect) { this.apply(); changed = true; }
      // a door closed over the doorway (the Animate tab): eased back into the cabin
      const r = project(this.p, this.doors());
      if (r.d > 1e-4) {
        const a = 1 - Math.exp(-6 * dt);
        this.p = this.p.map((v, i) => v + (r.p[i] - v) * (r.d < 0.002 ? 1 : a));
        this.apply();
        changed = true;
      }
    }
    return changed;
  }

  // integrate the walk / turn / wheel inputs over dt; returns true when the pose changed
  step(dt, input = null) {
    if (dt <= 0) return false;
    const k = this.keys, has = (...c) => c.some((x) => k.has(x));
    const run = has('ShiftLeft', 'ShiftRight') ? SPEED.run : SPEED.walk;
    let f = 0, s = 0, u = 0, turn = 0, look = 0;
    if (input) ({ f = 0, s = 0, u = 0, turn = 0 } = input);
    else {
      f = (has('KeyW', 'ArrowUp') ? 1 : 0) - (has('KeyS', 'ArrowDown') ? 1 : 0) + this.pad.f;
      s = (has('KeyD') ? 1 : 0) - (has('KeyA') ? 1 : 0) + this.pad.s;
      u = (has('KeyE', 'PageUp') ? 1 : 0) - (has('KeyQ', 'PageDown') ? 1 : 0) + this.pad.u;
      turn = (has('ArrowLeft') ? 1 : 0) - (has('ArrowRight') ? 1 : 0);
      look = (has('KeyR') ? 1 : 0) - (has('KeyF') ? 1 : 0);
    }
    // the latch holds while the same strafe is held (released or reversed, it lets go: NAV2-02)
    const sDir = Math.sign(clamp(s, -1, 1));
    if (this.latch && sDir !== this.latch.dir) this.latch = null;
    const want = [clamp(f, -1, 1) * run, clamp(s, -1, 1) * run, clamp(u, -1, 1) * SPEED.lift];
    const a = input ? 1 : 1 - Math.exp(-SPEED.accel * dt);
    let moving = false;
    for (let i = 0; i < 3; i++) {
      this.vel[i] += (want[i] - this.vel[i]) * a;
      if (Math.abs(this.vel[i]) < 1e-3 && want[i] === 0) this.vel[i] = 0;
      if (this.vel[i]) moving = true;
    }
    const tw = turn * SPEED.turn;
    this.turnVel += (tw - this.turnVel) * a;
    if (Math.abs(this.turnVel) < 1e-3 && !tw) this.turnVel = 0;
    let rot = false;
    if (tw || look) this.seatTurn = null;                // the user's own turn wins
    if (look) this.pitchAuto = false;                    // ... and the user's own pitch
    if ((moving || tw || look || this.pending) && !input && this.onInput) this.onInput();
    if (this.seatTurn) {                                 // eased to the seat's facing (NAV2-03)
      const T = this.seatTurn;
      T.t += dt;
      const e = smooth(clamp(T.t / SEAT_TURN, 0, 1));
      this.yaw = lerpAngle(T.yaw0, T.yaw1, e);
      this.pitch = T.pitch0 + (T.pitch1 - T.pitch0) * e;
      if (e >= 1) this.seatTurn = null;
      rot = true;
    }
    if (this.turnVel) { this.yaw = wrap(this.yaw + this.turnVel * dt); rot = true; }
    if (look) { this.pitch = clamp(this.pitch + look * SPEED.pitch * dt, -PITCH_MAX, PITCH_MAX); rot = true; }
    let fwd = this.vel[0] * dt;
    if (this.pending) {
      const take = Math.abs(this.pending) < 0.002 ? this.pending : this.pending * (1 - Math.exp(-14 * dt));
      this.pending -= take;
      fwd += take;
      moving = true;
    }
    const rising = Math.abs(this.zWant - this.p[2]) > 1e-4;      // rising to (or sinking to) the kept height
    if (!moving && !rot && !rising) return false;
    const p0 = this.p;
    if (moving || rising) {
      const cy = Math.cos(this.yaw), sy = Math.sin(this.yaw);
      const sd = this.vel[1] * dt, ud = this.vel[2] * dt;
      // the kept eye height: Q / E move it (lowering starts from where the eye is, under a low ceiling too)
      if (ud < 0) this.zWant = Math.min(this.zWant, this.p[2] + 0.02);
      this.zWant = clamp(this.zWant + ud, TOUR.crouch_min, TOUR.floor + TOUR.cabin_height);
      // forward along the heading (level), right = heading x up; the eye rises back to the kept height gently
      const q = [this.p[0] + fwd * cy + sd * sy, this.p[1] + fwd * sy - sd * cy,
        clamp(this.zWant, this.p[2] - SINK * dt, this.p[2] + RISE * dt)];
      const x0 = this.p[0], y0 = this.p[1];
      const L = this.latch;
      if (L && L.seat) {                       // on into the seat, whichever way the turning view points the step
        q[0] = x0 + fwd * cy;
        q[1] = y0 + clamp(L.y - y0, -Math.abs(sd), Math.abs(sd));
      }
      else if (L) q[1] = L.side > 0 ? clamp(q[1], Math.min(y0, L.y), L.y) : clamp(q[1], L.y, Math.max(y0, L.y));
      // the aisle's aft end while looking aft: FACE_CLEAR short of the baggage partition (tour_data face_x1, NAV3-04);
      // the gap between the crew seats while looking forward: level with the seated eyes (face_x0, NAV3-01)
      const Rf = this.region ? regionById(this.region) : null;
      if (Rf && Rf.face_x1 != null && q[0] > x0 && cy > 0.5 && q[0] > Rf.face_x1) q[0] = Math.max(x0, Rf.face_x1);
      if (Rf && Rf.face_x0 != null && q[0] < x0 && cy < -0.5 && q[0] < Rf.face_x0) q[0] = Math.min(x0, Rf.face_x0);
      const strafe = Math.abs(sd) > 1e-6 ? sDir : 0;
      this.moveTo(q, strafe);
      // a sidestep held by the aisle's edge next to a seat slides along the aisle into that seat (review r1 NAV1-07:
      // the seats could only be reached from the menu, so a sidestep felt stuck rather than blocked)
      const dy = q[1] - y0;
      if (!L && strafe && Math.abs(dy) > 1e-6 && Math.abs(this.p[1] - y0) < 0.3 * Math.abs(dy)) this._pullToSeat(dy, Math.abs(sd), strafe);
      // a sidestep in a seat held by its outboard side slides back toward the aisle / the gap between the crew seats
      // when the walk into the seat turned the view round (review r3 NAV3-05: in an aft-facing seat reached from a
      // forward walk the turned view reverses the strafe, and the arrow that is not the way in pushed the eye into the
      // side wall); not while a step into the seat is still carried on (latch)
      if (!this.latch && this.seatFlip && strafe && this.region && this.region.startsWith('seat_') && Math.abs(dy) > 1e-6 &&
          Math.abs(this.p[1] - y0) < 0.3 * Math.abs(dy)) {
        const R = regionById(this.region), out = R ? Math.sign(R.y[0] + R.y[1]) : 0;
        if (out && Math.sign(dy) === out) {
          // carried on to the aisle / gap centre line while the strafe is held (the view-relative step would push it
          // straight back out); entering the aisle the usual centre-line latch takes over
          const W = regionById(this.region === 'seat_pilot' || this.region === 'seat_copilot' ? 'crew_gap' : 'aisle');
          const yc = W ? 0.5 * (W.y[0] + W.y[1]) : 0;
          this.latch = { dir: strafe, y: yc, side: -out, seat: true };
          this.moveTo([this.p[0], this.p[1] - out * Math.abs(dy), this.p[2]], strafe);
        }
      }
      // an aft step held by a crew seat's pocket slides inboard into the gap between the seats, the way out (NAV2-02)
      const dx = q[0] - x0;
      if (dx > 1e-6 && (this.region === 'seat_pilot' || this.region === 'seat_copilot') && this.p[0] - x0 < 0.3 * dx) {
        const G = regionById('crew_gap');
        if (G) {
          const yc = 0.5 * (G.y[0] + G.y[1]);
          this.moveTo([this.p[0] + dx, this.p[1] + Math.sign(yc - this.p[1]) * Math.min(Math.abs(yc - this.p[1]), dx), this.p[2]]);
        }
      }
      // ... and the way back in (review r3 NAV3-01): a forward step held at the flight deck's front face, between the
      // seat backs, carries on down into that gap at the seated eye height (a standing or a fully crouched eye
      // always projected onto the flight deck instead); a sidestep from the gap then enters either crew seat
      if (dx < -1e-6 && this.region === 'flight_deck' && x0 - this.p[0] < 0.3 * -dx) {
        const FD = regionById('flight_deck'), G = regionById('crew_gap');
        if (FD && G && this.p[0] <= FD.x[0] + 1e-3) {
          this.zWant = Math.min(this.zWant, G.eye_z != null ? G.eye_z : G.z[1] - 0.02);   // then glides down (SINK)
          this.moveTo([this.p[0] + dx, this.p[1], Math.min(this.p[2], G.z[1] - 0.02)]);
        }
      }
    }
    // a walk levels a stop's steep look (NAV3-03)
    const walked = Math.hypot(this.p[0] - p0[0], this.p[1] - p0[1]) > 1e-6;
    if (walked && this.pitchAuto && !this.seatTurn && LEVELING.has(this.region)) {
      const e = 1 - Math.exp(-3 * dt / LEVEL_TIME);
      this.pitch += (WALK_PITCH - this.pitch) * e;
      if (Math.abs(this.pitch - WALK_PITCH) < 0.25 * D2R) { this.pitch = WALK_PITCH; this.pitchAuto = false; }
      rot = true;
    }
    const moved = Math.abs(this.p[0] - p0[0]) + Math.abs(this.p[1] - p0[1]) + Math.abs(this.p[2] - p0[2]) > 1e-6;
    if (!moved && !rot) return false;           // held by a ceiling: nothing to draw
    const left = this.stop && moving && moved;
    if (left) this.stop = null;
    this.apply();
    // the stop button / live region follow the walk (review r4 NAV8-04)
    if (left || this.region !== this._regionSaid) { this._regionSaid = this.region; this.hooks.changed(); }
    return true;
  }

  // move the eye to q, held inside the walkable volume (slides along the walls: the box clamp keeps the free axes);
  // stepping out of a seat (or the gap between the crew seats) into the aisle / vestibule / flight deck stands the
  // walker up again
  // strafe: the sign of a held sideways step (0: none).  A sideways step out of a seat into the aisle / the gap between
  // the crew seats is held on that region's centre line until the strafe is released and pressed again (review r2
  // NAV2-02: the aisle is 0.2 m wide, a held key crossed it in 0.2 s into the opposite seat); a walk into a seat turns
  // the view to the seat's facing (NAV2-03: a sidestep into a forward-facing seat while looking aft put the face in its
  // own headrest) and holds a sideways step on the seated eye's line (the turned view would otherwise walk back out)
  moveTo(q, strafe = 0) {
    const r = project(q, this.doors(), ZW);
    const was = this.region;
    const y0 = this.p[1];
    this.p = r.p;
    this.region = r.region;
    const seated = (id) => !!id && (id.startsWith('seat_') || id === 'crew_gap');
    if (seated(was) && r.region && !seated(r.region)) this.zWant = Math.max(this.zWant, TOUR.stand_eye);
    if (was === r.region || !r.region) return;
    if (!r.region.startsWith('seat_')) this.seatFlip = false;
    const R = TOUR.regions.find((g) => g.id === r.region);
    if (strafe && was && was.startsWith('seat_') && STANDING.has(r.region)) {
      const yc = 0.5 * (R.y[0] + R.y[1]);
      // a seat-type latch (the step out of a turned seat, whichever way the view points) stays one on the way to the
      // centre line: built from the strafe instead, a strafe pointing back at the seat held the eye on the aisle's
      // edge and the drift after the release took it back into the seat (review r4 NAV8-02)
      const carried = !!(this.latch && this.latch.seat);
      this.latch = { dir: strafe, y: yc, side: Math.sign(yc - y0) || 1, seat: carried };
      if ((this.p[1] - yc) * this.latch.side > 0) this.moveTo([this.p[0], yc, this.p[2]]);
    } else if (r.region.startsWith('seat_') && (!was || STANDING.has(was)) && R && R.facing) {
      this.seatTurn = { t: 0, yaw0: this.yaw, yaw1: R.facing > 0 ? Math.PI : 0, pitch0: this.pitch,
        pitch1: R.pitch != null ? R.pitch * D2R : SEAT_PITCH };
      this.seatFlip = Math.abs(wrap(this.seatTurn.yaw1 - this.yaw)) > Math.PI / 2;
      // the held step carries on to the seated eye's BL (the turned view would otherwise walk it back out)
      if (strafe && R.eye_bl != null) this.latch = { dir: strafe, y: R.eye_bl, side: Math.sign(R.eye_bl - y0) || 1, seat: true };
    }
  }

  // the nearest seat pocket on the side of a blocked sidestep (dy: the wanted lateral move) within SIDESTEP_PULL
  // along the aisle: the eye slides toward it by up to `step` (it enters the seat once level with it)
  _pullToSeat(dy, step, strafe = 0) {
    if (this.region !== 'aisle' && this.region !== 'vestibule') return;
    const x = this.p[0];
    let best = null, bd = SIDESTEP_PULL;
    for (const R of TOUR.regions) {
      if (!R.id.startsWith('seat_')) continue;
      const side = 0.5 * (R.y[0] + R.y[1]);
      if (Math.sign(side) !== Math.sign(dy)) continue;
      const d = x < R.x[0] ? R.x[0] - x : x > R.x[1] ? x - R.x[1] : 0;
      if (d < bd) { bd = d; best = R; }
    }
    if (!best) return;
    const cx = 0.5 * (best.x[0] + best.x[1]);
    const mx = Math.sign(cx - x) * Math.min(Math.abs(cx - x), step);
    this.moveTo([x + mx, this.p[1] + dy, this.p[2]], strafe);
  }

  look(dyaw, dpitch) {
    this.seatTurn = null;
    if (dpitch) this.pitchAuto = false;
    if (this.onInput) this.onInput();
    this.yaw = wrap(this.yaw + dyaw);
    this.pitch = clamp(this.pitch + dpitch, -PITCH_MAX, PITCH_MAX);
    if (this.tasks.length) this.finish();
    this.apply();
  }

  // ---------------------------------------------------------------- input
  // keys: handled (true) only while inside and not flying through the exterior leg
  keydown(e) {
    const c = e.code;
    const walk = ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'KeyQ', 'KeyE', 'KeyR', 'KeyF', 'ArrowUp', 'ArrowDown', 'ArrowLeft',
      'ArrowRight', 'PageUp', 'PageDown', 'ShiftLeft', 'ShiftRight'];
    if (!walk.includes(c)) return false;
    if (this.tasks.length && c !== 'ShiftLeft' && c !== 'ShiftRight') this.finish();
    this.keys.add(c);
    return true;
  }
  keyup(e) {
    this.keys.delete(e.code);
    if (e.code === 'KeyA' || e.code === 'KeyD') this.strafeUp();
  }
  // a released sideways step stops at once in and round the seats (the walk's velocity smoothing drifted the eye
  // ~0.1 m on: back into a seat after a step out, off the seated eye after a step in -- review r4 NAV8-02)
  strafeUp() {
    const seatish = this.latch || (this.region && (this.region.startsWith('seat_') || this.region === 'crew_gap'));
    if (seatish) this.vel[1] = 0;
    this.latch = null;
  }
  blur() { this.keys.clear(); this.pad = { f: 0, s: 0, u: 0 }; this.latch = null; }

  _wirePointer(cv) {
    const P = this.pointers;
    const k = () => (this.stage.camera.fov * D2R) / Math.max(200, this.stage.visible ? this.stage.visible.h : cv.clientHeight);
    let pinch = null;
    const two = () => {
      const [a, b] = [...P.values()];
      return { d: Math.hypot(a.x - b.x, a.y - b.y), x: 0.5 * (a.x + b.x), y: 0.5 * (a.y + b.y) };
    };
    cv.addEventListener('pointerdown', (e) => {
      if (!this.active) return;
      P.set(e.pointerId, { x: e.clientX, y: e.clientY });
      try { cv.setPointerCapture(e.pointerId); } catch (err) { /* synthetic events */ }
      pinch = P.size === 2 ? two() : null;
    });
    cv.addEventListener('pointermove', (e) => {
      if (!this.active || !P.has(e.pointerId)) return;
      const o = P.get(e.pointerId);
      const dx = e.clientX - o.x, dy = e.clientY - o.y;
      o.x = e.clientX; o.y = e.clientY;
      if (P.size === 1) {
        // drag the view: the scene follows the pointer (grab), so a drag to the right turns the view left
        this.look(dx * k(), dy * k());
      } else if (P.size === 2 && pinch) {
        const n = two();
        const spread = n.d - pinch.d, mdx = n.x - pinch.x, mdy = n.y - pinch.y;
        pinch = n;
        this.pending += spread * PINCH_M - mdy * PINCH_M;
        if (mdx) {
          const sd = -mdx * PINCH_M, cy = Math.cos(this.yaw), sy = Math.sin(this.yaw);
          this.moveTo([this.p[0] + sd * sy, this.p[1] - sd * cy, this.p[2]]);
          this.stop = null;
          this.apply();
        }
      }
    });
    const up = (e) => {
      P.delete(e.pointerId);
      pinch = P.size === 2 ? two() : null;
    };
    cv.addEventListener('pointerup', up);
    cv.addEventListener('pointercancel', up);
    cv.addEventListener('lostpointercapture', up);
    cv.addEventListener('contextmenu', (e) => { if (this.active) e.preventDefault(); });
    cv.addEventListener('wheel', (e) => {
      if (!this.active) return;
      e.preventDefault();
      const px = e.deltaMode === 1 ? e.deltaY * 40 : e.deltaMode === 2 ? e.deltaY * 400 : e.deltaY;
      this.pending += -clamp(px, -240, 240) * WHEEL_M;
      if (this.tasks.length) this.finish();
    }, { passive: false });
  }

  // ---------------------------------------------------------------- test / debug
  state() {
    const r = project(this.p, this.doors());
    return {
      active: this.active, stop: this.stop, lastStop: this.lastStop, flying: this.flying,
      pos: this.p.map((v) => Math.round(v * 1e5) / 1e5), yawDeg: this.yaw / D2R, pitchDeg: this.pitch / D2R,
      fov: this.stage.camera.fov, region: r.region, outside: r.d, fade: this.fade ? +this.fade.style.opacity || 0 : 0,
      latched: !!this.latch, seatTurn: !!this.seatTurn, seatFlip: this.seatFlip, pitchAuto: this.pitchAuto,
    };
  }
  // integrate a held input {f, s, u, turn} (-1 .. 1) for sec seconds in 1/60 s steps (the key path, unsmoothed)
  walk(input, sec) {
    this.finish();
    this.latch = null;                       // each call is a fresh press
    for (let t = 0; t < sec - 1e-9; t += 1 / 60) this.step(Math.min(1 / 60, sec - t), input);
    this.vel = [0, 0, 0]; this.turnVel = 0;
    return this.state();
  }
}

// ---------------------------------------------------------------------------------------------------- UI
// The toolbar's interior group (Go inside / Exit / stop menu / prev / next), the stop menu, the controls hint and the
// on-screen walk pad.  ui.sync() after every state change.
export class TourUI {
  constructor(tour, { onEnterRequest }) {
    this.tour = tour;
    const $ = (id) => document.getElementById(id);
    this.el = {
      enter: $('tourEnter'), exit: $('tourExit'), prev: $('tourPrev'), next: $('tourNext'), stop: $('tourStop'),
      stopLabel: $('tourStopLabel'), menu: $('tourMenu'), hint: $('tourHint'), hintText: $('tourHintText'),
      hintClose: $('tourHintClose'), pad: $('tourPad'), app: $('app'), live: $('tourLive'),
    };
    this._said = null;
    this.hintDismissed = false;
    this.hintTimer = null;
    // the hint fades HINT_FADE s after the first look / walk input inside (review r3 NAV3-02: it covered the bottom of
    // the airstair view, the treads)
    tour.onInput = () => {
      if (this.hintTimer || this.el.hint.hidden) return;
      this.hintTimer = setTimeout(() => this.fadeHint(), HINT_FADE * 1000);
    };
    this.menuFrom = null;
    const E = this.el;
    // menu items: number, name, one-line note
    TOUR.stops.forEach((s, i) => {
      const b = document.createElement('button');
      b.type = 'button';
      b.setAttribute('role', 'menuitemradio');
      b.setAttribute('aria-checked', 'false');
      b.dataset.stop = s.id;
      b.tabIndex = -1;
      b.innerHTML = '<span class="tm-n"></span><span class="tm-t"><b></b><span class="muted"></span></span>';
      b.querySelector('.tm-n').textContent = String(i + 1);
      b.querySelector('b').textContent = s.label;
      b.querySelector('.muted').textContent = s.note;
      b.addEventListener('click', () => {
        this.closeMenu(false);
        onEnterRequest(s.id);
        // keyboard users land on the stop button (arrows / WASD keep walking from there)
        if (tour.active) this.el.stop.focus({ preventScroll: true });
      });
      E.menu.append(b);
    });
    E.enter.addEventListener('click', () => this.toggleMenu(E.enter));
    E.stop.addEventListener('click', () => this.toggleMenu(E.stop));
    E.exit.addEventListener('click', () => tour.exit());
    E.prev.addEventListener('click', () => tour.next(-1));
    E.next.addEventListener('click', () => tour.next(1));
    E.hintClose.addEventListener('click', () => { this.hintDismissed = true; E.hint.hidden = true; });
    E.menu.addEventListener('keydown', (e) => this._menuKey(e));
    document.addEventListener('pointerdown', (e) => {
      if (E.menu.hidden) return;
      if (E.menu.contains(e.target) || (this.menuFrom && this.menuFrom.contains(e.target))) return;
      this.closeMenu(false);
    }, true);
    window.addEventListener('resize', () => { if (!E.menu.hidden) this._place(); });
    // a touch anywhere shows the walk pad on a device whose primary pointer is fine (viewer.css)
    document.addEventListener('pointerdown', (e) => { if (e.pointerType === 'touch') E.app.classList.add('touch-used'); }, true);
    // walk pad: hold to walk (pointer), or a step per activation (keyboard)
    for (const b of E.pad.querySelectorAll('[data-walk]')) {
      const [axis, v] = b.dataset.walk.split(':');
      const set = (on) => { tour.pad[axis] = on ? +v : 0; if (!on && axis === 's') tour.strafeUp(); };
      b.addEventListener('pointerdown', (e) => { e.preventDefault(); try { b.setPointerCapture(e.pointerId); } catch (err) { /* */ } set(true); });
      for (const ev of ['pointerup', 'pointercancel', 'lostpointercapture']) b.addEventListener(ev, () => set(false));
      b.addEventListener('click', (e) => { if (e.detail === 0) tour.walk({ [axis]: +v }, 0.3); });
    }
  }

  toggleMenu(from) { if (this.el.menu.hidden) this.openMenu(from); else this.closeMenu(true); }
  openMenu(from = this.tour.active ? this.el.stop : this.el.enter, focus = true) {
    const E = this.el;
    this.menuFrom = from;
    E.menu.hidden = false;
    from.setAttribute('aria-expanded', 'true');
    this._place();
    const items = [...E.menu.querySelectorAll('[role^="menuitem"]')];
    const cur = items.find((b) => b.dataset.stop === (this.tour.active ? this.tour.lastStop : null)) || items[0];
    if (focus) cur.focus();
  }
  closeMenu(refocus = true) {
    const E = this.el;
    if (E.menu.hidden) return;
    E.menu.hidden = true;
    for (const b of [E.enter, E.stop]) b.setAttribute('aria-expanded', 'false');
    if (refocus && this.menuFrom && !this.menuFrom.hidden) this.menuFrom.focus();
    this.menuFrom = null;
  }
  _place() {
    const E = this.el, from = this.menuFrom || E.enter;
    const r = from.getBoundingClientRect(), app = E.app.getBoundingClientRect();
    const w = Math.min(320, app.width - 32);
    const left = clamp(r.left - app.left, 16, Math.max(16, app.width - w - 16));
    E.menu.style.left = `${left}px`;
    E.menu.style.top = `${r.bottom - app.top + 6}px`;
    E.menu.style.width = `${w}px`;
    E.menu.style.maxHeight = `${Math.max(160, app.bottom - r.bottom - 16)}px`;
  }
  _menuKey(e) {
    const items = [...this.el.menu.querySelectorAll('[role^="menuitem"]')];
    const i = items.indexOf(document.activeElement);
    let j = null;
    if (e.key === 'ArrowDown') j = (i + 1) % items.length;
    else if (e.key === 'ArrowUp') j = (i - 1 + items.length) % items.length;
    else if (e.key === 'Home') j = 0;
    else if (e.key === 'End') j = items.length - 1;
    else if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); this.closeMenu(true); return; }
    else if (e.key === 'Tab') { this.closeMenu(false); return; }
    else if (/^[1-9]$/.test(e.key) && items[+e.key - 1]) { e.preventDefault(); e.stopPropagation(); items[+e.key - 1].click(); return; }
    if (j == null) { e.stopPropagation(); return; }
    e.preventDefault();
    e.stopPropagation();
    items[j].focus();
  }

  fadeHint() {
    const h = this.el.hint;
    this.hintDismissed = true;
    if (h.hidden) return;
    h.classList.add('fading');
    setTimeout(() => { h.hidden = true; h.classList.remove('fading'); }, 450);
  }

  showHint() {
    if (this.hintDismissed) return;
    const coarse = !!(window.matchMedia && matchMedia('(pointer: coarse)').matches);
    this.el.hintText.textContent = coarse
      ? 'Drag to look · pinch / arrows to move'
      : 'Drag to look · W A S D or arrows to walk · wheel to move · 1–7 stops · Esc to exit';
    this.el.hint.hidden = false;
  }

  sync() {
    const t = this.tour, E = this.el, on = t.active;
    E.app.classList.toggle('touring', on);
    E.enter.hidden = on;
    for (const b of [E.exit, E.prev, E.next, E.stop]) b.hidden = !on;
    // at a stop (or flying to one) its label; walked away from it, where the eye is (review r4 NAV8-04: the button kept
    // the last stop's label -- 'Club seats' seated in the co-pilot seat); the menu marks a stop only while at it
    const s = t.stop ? stopById(t.stop) : null;
    const where = s ? s.label : on ? regionLabel(t.region) : null;
    const label = where || (stopById(t.lastStop) || {}).label || 'Stops';
    E.stopLabel.textContent = label;
    E.stop.setAttribute('aria-label', `Interior: ${where || 'none'}. Choose a stop`);
    for (const b of E.menu.querySelectorAll('[data-stop]')) b.setAttribute('aria-checked', String(on && !!s && b.dataset.stop === s.id));
    E.pad.hidden = !on;
    if (!on) E.hint.hidden = true;
    // at the airstair door the hint sits under the toolbar and the walk pad goes right, translucent: the treads fill
    // the bottom-left of that view (NAV3-02, NAV8-05)
    E.hint.classList.toggle('top', on && t.lastStop === 'airstair');
    E.pad.classList.toggle('aside', on && !!s && s.id === 'airstair');
    if (!E.menu.hidden) this._place();
    // screen readers: where the camera went
    const say = on ? (s ? `Inside: ${s.label}. ${s.note}.` : `Inside: ${where || 'cabin'}`) : this._said ? 'Back outside' : null;
    if (say && say !== this._said && E.live) E.live.textContent = say;
    this._said = on ? say : null;
  }
}
