// Interior tour: named stops in the flight deck and cabin, smooth camera flights between them, and a first-person
// camera while inside (drag to look, keys / wheel / pinch / on-screen arrows to walk), held inside the walkable volume
// of web/viewer/tour_data.js (generated by web/tour_data.py from the interior tables of model/interior.py).
//
// Coordinates: tour_data is in MODEL axes (x = STA aft, y = BL starboard, z = WL up); the scene is glTF
// (X = y, Y = z, Z = x).  The first-person pose is p (model, the eye point), yaw (heading in the x-y plane: 0 = aft,
// pi = forward) and pitch (up +).  The OrbitControls are switched off while inside; the camera looks at a point 0.3 m
// ahead, so the stage's near plane follows to 1 cm.
import * as THREE from 'three';
import { TOUR } from './tour_data.js';

export { TOUR };
const D2R = Math.PI / 180;
const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const smooth = (t) => t * t * (3 - 2 * t);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);
const wrap = (a) => Math.atan2(Math.sin(a), Math.cos(a));
const lerpAngle = (a, b, t) => a + wrap(b - a) * t;
export const toGL = (p) => new THREE.Vector3(p[1], p[2], p[0]);
export const toModel = (v) => [v.z, v.x, v.y];
const RM = window.matchMedia ? matchMedia('(prefers-reduced-motion: reduce)') : null;

// walking (m/s, rad/s), look sensitivity, limits
const SPEED = { walk: 1.0, run: 2.0, lift: 0.5, turn: 95 * D2R, pitch: 70 * D2R, accel: 10 };
const PITCH_MAX = 80 * D2R;
const WHEEL_M = 0.0022;                 // m per wheel pixel (a 100 px notch = 0.22 m)
const PINCH_M = 0.006;                  // m per pixel of pinch spread / two-finger drag
const FOV_MAX = 95, H_FOV_MIN = 70;    // widen the vertical FOV until at least 70 deg show across
const ZW = 0.1;                         // height weight of the walk projection (project)
const RISE = 0.6;                       // m/s: the eye coming back up to the kept height (standing up, a ceiling passed)

export function stopById(id) { return TOUR.stops.find((s) => s.id === id) || null; }
function angles(eye, target) {
  const dx = target[0] - eye[0], dy = target[1] - eye[1], dz = target[2] - eye[2];
  return { yaw: Math.atan2(dy, dx), pitch: Math.atan2(dz, Math.hypot(dx, dy)) };
}

// ---------------------------------------------------------------- walkable volume (the same rule as web/tour_data.py)
export function ceilingAt(x, a) {
  const C = TOUR.ceiling;
  const fx = clamp((x - C.x0) / C.dx, 0, C.nx - 1.000001), fa = clamp(a / C.da, 0, C.na - 1.000001);
  const i = fx | 0, j = fa | 0, u = fx - i, v = fa - j, z = C.z;
  return (z[i][j] * (1 - v) + z[i][j + 1] * v) * (1 - u) + (z[i + 1][j] * (1 - v) + z[i + 1][j + 1] * v) * u;
}
// nearest point of the union of the active regions: {p, d, region}.  zw < 1 weighs height differences less: a walk
// goes on under a lower ceiling (soffit, side lining, flight deck) or into a seat, the eye dipping to fit, instead of
// stopping at the edge
export function project(p, doors = {}, zw = 1) {
  let best = null, bd = Infinity, who = null, bt = 0;
  for (const R of TOUR.regions) {
    if (R.when && !(doors[R.when] >= 0.999)) continue;
    const x = clamp(p[0], R.x[0], R.x[1]), y = clamp(p[1], R.y[0], R.y[1]);
    let zhi = R.z[1];
    if (R.ceil) zhi = Math.min(zhi, ceilingAt(x, Math.abs(y)));
    if (zhi < R.z[0]) continue;
    const z = clamp(p[2], R.z[0], zhi);
    const d = (x - p[0]) ** 2 + (y - p[1]) ** 2 + (zw * (z - p[2])) ** 2;
    if (d < bd) { bd = d; best = [x, y, z]; who = R.id; bt = (x - p[0]) ** 2 + (y - p[1]) ** 2 + (z - p[2]) ** 2; }
  }
  return { p: best || p.slice(), d: Math.sqrt(bt), region: who };
}

export class Tour {
  // stage: scene.js Stage; kin: Kinematics (door targets for the doorway region); hooks: {enter(stop), exit(to),
  // changed()} from main.js (state save / restore, UI sync)
  constructor({ stage, kin, hooks }) {
    this.stage = stage;
    this.kin = kin;
    this.hooks = hooks;
    this.active = false;            // the tour owns the camera (from the start of the flight in to the end of exit)
    this.inside = false;            // the camera is inside (after the fade into the cabin): lit as the cabin
    this.stop = null;               // the stop the camera is at / flying to (null once walked away)
    this.lastStop = null;           // for prev / next and the stop button
    this.p = TOUR.stops[0].eye.slice();
    this.zWant = this.p[2];         // the eye height the walker keeps (Q / E, a stop's eye); ceilings push it down
    this.region = null;
    this.yaw = 0; this.pitch = 0; this.fovBase = 70; this.fovKick = 0;
    this.tasks = [];                // the flight / fade sequence (update)
    this.keys = new Set();
    this.pad = { f: 0, s: 0, u: 0 };
    this.vel = [0, 0, 0];           // forward, right, up (m/s), smoothed
    this.turnVel = 0;
    this.pending = 0;               // wheel / pinch travel still to cover (m, forward)
    this.pointers = new Map();
    this.fade = document.getElementById('tourFade');
    this.motionOverride = null;     // tests: force flights on (true) / off (false) regardless of reduced motion
    this._wirePointer(stage.renderer.domElement);
  }

  get motion() { return this.motionOverride != null ? this.motionOverride : !(RM && RM.matches); }
  get flying() { return this.tasks.length > 0; }
  doors() { const t = this.kin.t; return { door_airstair: t.door_airstair, door_cargo: t.door_cargo }; }

  // ---------------------------------------------------------------- camera
  dir() {
    const cp = Math.cos(this.pitch);
    return [cp * Math.cos(this.yaw), cp * Math.sin(this.yaw), Math.sin(this.pitch)];
  }
  fovFor(base) {
    const asp = Math.max(0.2, this.stage.camera.aspect);
    const need = 2 * Math.atan(Math.tan(H_FOV_MIN * D2R / 2) / asp) / D2R;
    return clamp(Math.max(base, need), 20, FOV_MAX);
  }
  apply() {
    const cam = this.stage.camera, c = this.stage.controls, d = this.dir();
    cam.position.copy(toGL(this.p));
    c.target.copy(toGL([this.p[0] + 0.3 * d[0], this.p[1] + 0.3 * d[1], this.p[2] + 0.3 * d[2]]));
    cam.lookAt(c.target);
    const fov = this.fovFor(this.fovBase) + this.fovKick;
    if (Math.abs(cam.fov - fov) > 1e-3) { cam.fov = fov; cam.updateProjectionMatrix(); }
    this._aspect = cam.aspect;
    this.stage.needsRender = true;
  }
  setPose(stop) {
    const s = typeof stop === 'string' ? stopById(stop) : stop;
    const a = angles(s.eye, s.target);
    this.p = s.eye.slice();
    this.zWant = s.eye[2];
    this.region = project(this.p, this.doors()).region;
    this.yaw = a.yaw; this.pitch = a.pitch; this.fovBase = s.fov;
  }
  _setFade(o) {
    if (!this.fade) return;
    this.fade.style.opacity = String(clamp(o, 0, 1));
    this.fade.hidden = o <= 0.001;
  }

  // ---------------------------------------------------------------- enter / go / exit
  // Outside -> a stop: the exterior leg to the stop's approach pose (round the fuselage, not through it), a fade, the
  // cut inside, the fade back with a slight field-of-view settle.  Reduced motion: a cut.
  enter(id, { motion = this.motion } = {}) {
    const s = stopById(id) || TOUR.stops[0];
    if (this.active) { this.go(s.id, { motion }); return; }
    this.tasks = [];
    const st = this.stage, cam = st.camera, c = st.controls;
    st.tween = null;
    st.preset = null;
    c.enableDamping = false; c.update(); c.enableDamping = true;
    c.enabled = false;
    this.active = true;
    this.stop = s.id;
    this.lastStop = s.id;
    this.hooks.enter(s, motion);               // saves the exterior state, sets the scene up (doors, cutaway off ...)
    const cut = () => { this.inside = true; this.setPose(s); this.vel = [0, 0, 0]; this.pending = 0; this.apply(); };
    if (!motion) { cut(); this._setFade(0); this.hooks.changed(); return; }
    const A = TOUR.approach[s.approach] || TOUR.approach.door;
    const p0 = cam.position.clone(), t0 = c.target.clone(), f0 = cam.fov;
    const p1 = toGL(A.eye), t1 = toGL(A.target);
    const yc = 1.86;                                       // fuselage axis height (glTF Y), for the orbit round it
    const cyl = (v) => ({ th: Math.atan2(v.y - yc, v.x), r: Math.hypot(v.x, v.y - yc), z: v.z });
    const c0 = cyl(p0), c1 = cyl(p1);
    const dist = p0.distanceTo(p1);
    this.tasks.push({
      dur: clamp(0.6 + dist / 14, 0.9, 1.8),
      run: (f) => {
        const e = ease(f);
        const th = lerpAngle(c0.th, c1.th, e), r = c0.r + (c1.r - c0.r) * e, z = c0.z + (c1.z - c0.z) * e;
        cam.position.set(r * Math.cos(th), yc + r * Math.sin(th), z);
        c.target.lerpVectors(t0, t1, e);
        cam.lookAt(c.target);
        cam.fov = f0 + (s.fov - f0) * e;
        cam.updateProjectionMatrix();
        this._setFade(smooth(clamp((f - 0.62) / 0.38, 0, 1)));
      },
    });
    this.tasks.push({ dur: 0, run: () => { cut(); this.fovKick = 9; this.apply(); this._setFade(1); } });
    this.tasks.push({
      dur: 0.55,
      run: (f) => { this._setFade(1 - smooth(f)); this.fovKick = 9 * (1 - ease(f)); this.apply(); },
    });
    this.hooks.changed();
  }

  // inside -> a stop: a flight along stop -> via -> aisle -> via -> stop (Catmull-Rom, arc length), looking where
  // it goes in the middle of a long flight
  go(id, { motion = this.motion } = {}) {
    const s = stopById(id);
    if (!s) return;
    if (!this.active) { this.enter(id, { motion }); return; }
    this.finish();
    this.stop = s.id;
    this.lastStop = s.id;
    if (s.doors) for (const k in s.doors) this.hooks.door(k, s.doors[k], motion);
    if (!motion) { this.setPose(s); this.apply(); this.hooks.changed(); return; }
    const pts = [this.p.slice()];
    const here = project(this.p, this.doors());
    if (Math.abs(this.p[1]) > TOUR.aisle_band + 1e-3) {
      const y = Math.sign(this.p[1]) * (TOUR.aisle_band - 0.01);
      if (here.region === 'doorway') pts.push([this.p[0], -0.33, this.p[2]]);
      pts.push(project([this.p[0], y, Math.max(this.p[2], TOUR.crouch_min + 0.1)], this.doors()).p);
    }
    for (const v of s.via.slice().reverse()) pts.push(v);
    pts.push(s.eye);
    const V = [];
    for (const q of pts) {
      const v = new THREE.Vector3(q[0], q[1], q[2]);
      if (!V.length || V[V.length - 1].distanceTo(v) > 0.02) V.push(v);
    }
    const a0 = { yaw: this.yaw, pitch: this.pitch }, a1 = angles(s.eye, s.target);
    const fov0 = this.fovBase;
    if (V.length < 2) { this.setPose(s); this.apply(); this.hooks.changed(); return; }
    const curve = new THREE.CatmullRomCurve3(V, false, 'centripetal');
    const len = curve.getLength();
    // looking where it goes in the middle of a long flight, only when both ends look roughly that way (the main
    // heading, start -> end): a stop behind the camera is reached backing up, not by turning round twice
    const main = Math.atan2(V[V.length - 1].y - V[0].y, V[V.length - 1].x - V[0].x);
    const along = (yw) => smooth(clamp((Math.cos(wrap(yw - main)) - 0.2) / 0.6, 0, 1));
    const look = len > 1.2 && Math.hypot(V[V.length - 1].x - V[0].x, V[V.length - 1].y - V[0].y) > 1.0
      ? 0.85 * Math.min(along(a0.yaw), along(a1.yaw)) : 0;
    this.tasks.push({
      dur: clamp(0.55 + len / 1.6, 0.8, 3.4),
      run: (f) => {
        const e = ease(f);
        const q = curve.getPointAt(e);
        this.p = [q.x, q.y, q.z];
        const b = smooth(clamp((f - 0.12) / 0.76, 0, 1));
        let yaw = lerpAngle(a0.yaw, a1.yaw, b), pitch = a0.pitch + (a1.pitch - a0.pitch) * b;
        if (look) {
          // the overall heading, not the local tangent: the sideways steps into / out of a seat do not swing the view
          const wt = look * smooth(clamp(f / 0.3, 0, 1)) * smooth(clamp((1 - f) / 0.3, 0, 1));
          yaw = lerpAngle(yaw, main, wt);
          pitch += (-6 * D2R - pitch) * wt;
        }
        this.yaw = yaw; this.pitch = pitch;
        this.fovBase = fov0 + (s.fov - fov0) * b;
        this.apply();
      },
    });
    this.tasks.push({ dur: 0, run: () => { this.setPose(s); this.apply(); } });
    this.hooks.changed();
  }

  // inside -> outside: fade, the exterior view and state restored (main.js), fade back.  to: a camera preset name
  exit({ motion = this.motion, to = 'three_quarter' } = {}) {
    if (!this.active) return;
    this.tasks = [];
    this.keys.clear(); this.pad = { f: 0, s: 0, u: 0 }; this.vel = [0, 0, 0]; this.turnVel = 0; this.pending = 0;
    const out = () => {
      this.active = false;
      this.inside = false;
      this.stop = null;
      this.fovKick = 0;
      this.stage.controls.enabled = true;
      this.hooks.exit(to);
    };
    if (!motion) { out(); this._setFade(0); this.hooks.changed(); return; }
    this.tasks.push({ dur: 0.28, run: (f) => this._setFade(smooth(f)) });
    this.tasks.push({ dur: 0, run: () => { out(); this._setFade(1); this.hooks.changed(); } });
    this.tasks.push({ dur: 0.45, run: (f) => this._setFade(1 - smooth(f)) });
    this.hooks.changed();
  }

  // complete a running flight / fade at once (tests, or a new command mid-flight)
  finish() {
    let guard = 0;
    while (this.tasks.length && guard++ < 20) {
      const k = this.tasks.shift();
      k.run(1);
    }
    this._setFade(0);
  }

  next(step = 1) {
    const n = TOUR.stops.length;
    const i = Math.max(0, TOUR.stops.findIndex((s) => s.id === this.lastStop));
    this.go(TOUR.stops[(i + step + n) % n].id);
  }

  // ---------------------------------------------------------------- per frame
  update(dt) {
    let changed = false;
    if (this.tasks.length) {
      let left = dt;
      while (this.tasks.length) {
        const k = this.tasks[0];
        k.t = (k.t || 0) + left;
        const f = k.dur > 0 ? Math.min(1, k.t / k.dur) : 1;
        k.run(f);
        changed = true;
        if (f < 1) break;
        left = k.dur > 0 ? k.t - k.dur : left;
        this.tasks.shift();
        if (!this.tasks.length) this.hooks.changed();
      }
      if (this.tasks.length) return true;
    }
    if (!this.active) return changed;
    if (this.step(dt)) changed = true;
    if (this.inside) {
      // the viewport changed shape (panel, rotation): the field of view follows
      if (this.stage.camera.aspect !== this._aspect) { this.apply(); changed = true; }
      // a door closed over the doorway (the Animate tab): eased back into the cabin
      const r = project(this.p, this.doors());
      if (r.d > 1e-4) {
        const a = 1 - Math.exp(-6 * dt);
        this.p = this.p.map((v, i) => v + (r.p[i] - v) * (r.d < 0.002 ? 1 : a));
        this.apply();
        changed = true;
      }
    }
    return changed;
  }

  // integrate the walk / turn / wheel inputs over dt; returns true when the pose changed
  step(dt, input = null) {
    if (dt <= 0) return false;
    const k = this.keys, has = (...c) => c.some((x) => k.has(x));
    const run = has('ShiftLeft', 'ShiftRight') ? SPEED.run : SPEED.walk;
    let f = 0, s = 0, u = 0, turn = 0, look = 0;
    if (input) ({ f = 0, s = 0, u = 0, turn = 0 } = input);
    else {
      f = (has('KeyW', 'ArrowUp') ? 1 : 0) - (has('KeyS', 'ArrowDown') ? 1 : 0) + this.pad.f;
      s = (has('KeyD') ? 1 : 0) - (has('KeyA') ? 1 : 0) + this.pad.s;
      u = (has('KeyE', 'PageUp') ? 1 : 0) - (has('KeyQ', 'PageDown') ? 1 : 0) + this.pad.u;
      turn = (has('ArrowLeft') ? 1 : 0) - (has('ArrowRight') ? 1 : 0);
      look = (has('KeyR') ? 1 : 0) - (has('KeyF') ? 1 : 0);
    }
    const want = [clamp(f, -1, 1) * run, clamp(s, -1, 1) * run, clamp(u, -1, 1) * SPEED.lift];
    const a = input ? 1 : 1 - Math.exp(-SPEED.accel * dt);
    let moving = false;
    for (let i = 0; i < 3; i++) {
      this.vel[i] += (want[i] - this.vel[i]) * a;
      if (Math.abs(this.vel[i]) < 1e-3 && want[i] === 0) this.vel[i] = 0;
      if (this.vel[i]) moving = true;
    }
    const tw = turn * SPEED.turn;
    this.turnVel += (tw - this.turnVel) * a;
    if (Math.abs(this.turnVel) < 1e-3 && !tw) this.turnVel = 0;
    let rot = false;
    if (this.turnVel) { this.yaw = wrap(this.yaw + this.turnVel * dt); rot = true; }
    if (look) { this.pitch = clamp(this.pitch + look * SPEED.pitch * dt, -PITCH_MAX, PITCH_MAX); rot = true; }
    let fwd = this.vel[0] * dt;
    if (this.pending) {
      const take = Math.abs(this.pending) < 0.002 ? this.pending : this.pending * (1 - Math.exp(-14 * dt));
      this.pending -= take;
      fwd += take;
      moving = true;
    }
    const rising = this.zWant > this.p[2] + 1e-4;
    if (!moving && !rot && !rising) return false;
    const p0 = this.p;
    if (moving || rising) {
      const cy = Math.cos(this.yaw), sy = Math.sin(this.yaw);
      const sd = this.vel[1] * dt, ud = this.vel[2] * dt;
      // the kept eye height: Q / E move it (lowering starts from where the eye is, under a low ceiling too)
      if (ud < 0) this.zWant = Math.min(this.zWant, this.p[2] + 0.02);
      this.zWant = clamp(this.zWant + ud, TOUR.crouch_min, TOUR.floor + TOUR.cabin_height);
      // forward along the heading (level), right = heading x up; the eye rises back to the kept height gently
      this.moveTo([this.p[0] + fwd * cy + sd * sy, this.p[1] + fwd * sy - sd * cy, Math.min(this.zWant, this.p[2] + RISE * dt)]);
    }
    const moved = Math.abs(this.p[0] - p0[0]) + Math.abs(this.p[1] - p0[1]) + Math.abs(this.p[2] - p0[2]) > 1e-6;
    if (!moved && !rot) return false;           // held by a ceiling: nothing to draw
    if (this.stop && moving && moved) this.stop = null;
    this.apply();
    return true;
  }

  // move the eye to q, held inside the walkable volume (slides along the walls: the box clamp keeps the free axes);
  // stepping out of a seat into the aisle / vestibule / flight deck stands the walker up again
  moveTo(q) {
    const r = project(q, this.doors(), ZW);
    const was = this.region;
    this.p = r.p;
    this.region = r.region;
    if (was && was.startsWith('seat_') && r.region && !r.region.startsWith('seat_')) this.zWant = Math.max(this.zWant, TOUR.stand_eye);
  }

  look(dyaw, dpitch) {
    this.yaw = wrap(this.yaw + dyaw);
    this.pitch = clamp(this.pitch + dpitch, -PITCH_MAX, PITCH_MAX);
    if (this.tasks.length) this.finish();
    this.apply();
  }

  // ---------------------------------------------------------------- input
  // keys: handled (true) only while inside and not flying through the exterior leg
  keydown(e) {
    const c = e.code;
    const walk = ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'KeyQ', 'KeyE', 'KeyR', 'KeyF', 'ArrowUp', 'ArrowDown', 'ArrowLeft',
      'ArrowRight', 'PageUp', 'PageDown', 'ShiftLeft', 'ShiftRight'];
    if (!walk.includes(c)) return false;
    if (this.tasks.length && c !== 'ShiftLeft' && c !== 'ShiftRight') this.finish();
    this.keys.add(c);
    return true;
  }
  keyup(e) { this.keys.delete(e.code); }
  blur() { this.keys.clear(); this.pad = { f: 0, s: 0, u: 0 }; }

  _wirePointer(cv) {
    const P = this.pointers;
    const k = () => (this.stage.camera.fov * D2R) / Math.max(200, this.stage.visible ? this.stage.visible.h : cv.clientHeight);
    let pinch = null;
    const two = () => {
      const [a, b] = [...P.values()];
      return { d: Math.hypot(a.x - b.x, a.y - b.y), x: 0.5 * (a.x + b.x), y: 0.5 * (a.y + b.y) };
    };
    cv.addEventListener('pointerdown', (e) => {
      if (!this.active) return;
      P.set(e.pointerId, { x: e.clientX, y: e.clientY });
      try { cv.setPointerCapture(e.pointerId); } catch (err) { /* synthetic events */ }
      pinch = P.size === 2 ? two() : null;
    });
    cv.addEventListener('pointermove', (e) => {
      if (!this.active || !P.has(e.pointerId)) return;
      const o = P.get(e.pointerId);
      const dx = e.clientX - o.x, dy = e.clientY - o.y;
      o.x = e.clientX; o.y = e.clientY;
      if (P.size === 1) {
        // drag the view: the scene follows the pointer (grab), so a drag to the right turns the view left
        this.look(dx * k(), dy * k());
      } else if (P.size === 2 && pinch) {
        const n = two();
        const spread = n.d - pinch.d, mdx = n.x - pinch.x, mdy = n.y - pinch.y;
        pinch = n;
        this.pending += spread * PINCH_M - mdy * PINCH_M;
        if (mdx) {
          const sd = -mdx * PINCH_M, cy = Math.cos(this.yaw), sy = Math.sin(this.yaw);
          this.moveTo([this.p[0] + sd * sy, this.p[1] - sd * cy, this.p[2]]);
          this.stop = null;
          this.apply();
        }
      }
    });
    const up = (e) => {
      P.delete(e.pointerId);
      pinch = P.size === 2 ? two() : null;
    };
    cv.addEventListener('pointerup', up);
    cv.addEventListener('pointercancel', up);
    cv.addEventListener('lostpointercapture', up);
    cv.addEventListener('contextmenu', (e) => { if (this.active) e.preventDefault(); });
    cv.addEventListener('wheel', (e) => {
      if (!this.active) return;
      e.preventDefault();
      const px = e.deltaMode === 1 ? e.deltaY * 40 : e.deltaMode === 2 ? e.deltaY * 400 : e.deltaY;
      this.pending += -clamp(px, -240, 240) * WHEEL_M;
      if (this.tasks.length) this.finish();
    }, { passive: false });
  }

  // ---------------------------------------------------------------- test / debug
  state() {
    const r = project(this.p, this.doors());
    return {
      active: this.active, stop: this.stop, lastStop: this.lastStop, flying: this.flying,
      pos: this.p.map((v) => Math.round(v * 1e5) / 1e5), yawDeg: this.yaw / D2R, pitchDeg: this.pitch / D2R,
      fov: this.stage.camera.fov, region: r.region, outside: r.d, fade: this.fade ? +this.fade.style.opacity || 0 : 0,
    };
  }
  // integrate a held input {f, s, u, turn} (-1 .. 1) for sec seconds in 1/60 s steps (the key path, unsmoothed)
  walk(input, sec) {
    this.finish();
    for (let t = 0; t < sec - 1e-9; t += 1 / 60) this.step(Math.min(1 / 60, sec - t), input);
    this.vel = [0, 0, 0]; this.turnVel = 0;
    return this.state();
  }
}

// ---------------------------------------------------------------------------------------------------- UI
// The toolbar's interior group (Go inside / Exit / stop menu / prev / next), the stop menu, the controls hint and the
// on-screen walk pad.  ui.sync() after every state change.
export class TourUI {
  constructor(tour, { onEnterRequest }) {
    this.tour = tour;
    const $ = (id) => document.getElementById(id);
    this.el = {
      enter: $('tourEnter'), exit: $('tourExit'), prev: $('tourPrev'), next: $('tourNext'), stop: $('tourStop'),
      stopLabel: $('tourStopLabel'), menu: $('tourMenu'), hint: $('tourHint'), hintText: $('tourHintText'),
      hintClose: $('tourHintClose'), pad: $('tourPad'), app: $('app'), live: $('tourLive'),
    };
    this._said = null;
    this.hintDismissed = false;
    this.menuFrom = null;
    const E = this.el;
    // menu items: number, name, one-line note
    TOUR.stops.forEach((s, i) => {
      const b = document.createElement('button');
      b.type = 'button';
      b.setAttribute('role', 'menuitemradio');
      b.setAttribute('aria-checked', 'false');
      b.dataset.stop = s.id;
      b.tabIndex = -1;
      b.innerHTML = '<span class="tm-n"></span><span class="tm-t"><b></b><span class="muted"></span></span>';
      b.querySelector('.tm-n').textContent = String(i + 1);
      b.querySelector('b').textContent = s.label;
      b.querySelector('.muted').textContent = s.note;
      b.addEventListener('click', () => {
        this.closeMenu(false);
        onEnterRequest(s.id);
        // keyboard users land on the stop button (arrows / WASD keep walking from there)
        if (tour.active) this.el.stop.focus({ preventScroll: true });
      });
      E.menu.append(b);
    });
    E.enter.addEventListener('click', () => this.toggleMenu(E.enter));
    E.stop.addEventListener('click', () => this.toggleMenu(E.stop));
    E.exit.addEventListener('click', () => tour.exit());
    E.prev.addEventListener('click', () => tour.next(-1));
    E.next.addEventListener('click', () => tour.next(1));
    E.hintClose.addEventListener('click', () => { this.hintDismissed = true; E.hint.hidden = true; });
    E.menu.addEventListener('keydown', (e) => this._menuKey(e));
    document.addEventListener('pointerdown', (e) => {
      if (E.menu.hidden) return;
      if (E.menu.contains(e.target) || (this.menuFrom && this.menuFrom.contains(e.target))) return;
      this.closeMenu(false);
    }, true);
    window.addEventListener('resize', () => { if (!E.menu.hidden) this._place(); });
    // walk pad: hold to walk (pointer), or a step per activation (keyboard)
    for (const b of E.pad.querySelectorAll('[data-walk]')) {
      const [axis, v] = b.dataset.walk.split(':');
      const set = (on) => { tour.pad[axis] = on ? +v : 0; };
      b.addEventListener('pointerdown', (e) => { e.preventDefault(); try { b.setPointerCapture(e.pointerId); } catch (err) { /* */ } set(true); });
      for (const ev of ['pointerup', 'pointercancel', 'lostpointercapture']) b.addEventListener(ev, () => set(false));
      b.addEventListener('click', (e) => { if (e.detail === 0) tour.walk({ [axis]: +v }, 0.3); });
    }
  }

  toggleMenu(from) { if (this.el.menu.hidden) this.openMenu(from); else this.closeMenu(true); }
  openMenu(from = this.tour.active ? this.el.stop : this.el.enter, focus = true) {
    const E = this.el;
    this.menuFrom = from;
    E.menu.hidden = false;
    from.setAttribute('aria-expanded', 'true');
    this._place();
    const items = [...E.menu.querySelectorAll('[role^="menuitem"]')];
    const cur = items.find((b) => b.dataset.stop === (this.tour.active ? this.tour.lastStop : null)) || items[0];
    if (focus) cur.focus();
  }
  closeMenu(refocus = true) {
    const E = this.el;
    if (E.menu.hidden) return;
    E.menu.hidden = true;
    for (const b of [E.enter, E.stop]) b.setAttribute('aria-expanded', 'false');
    if (refocus && this.menuFrom && !this.menuFrom.hidden) this.menuFrom.focus();
    this.menuFrom = null;
  }
  _place() {
    const E = this.el, from = this.menuFrom || E.enter;
    const r = from.getBoundingClientRect(), app = E.app.getBoundingClientRect();
    const w = Math.min(320, app.width - 32);
    const left = clamp(r.left - app.left, 16, Math.max(16, app.width - w - 16));
    E.menu.style.left = `${left}px`;
    E.menu.style.top = `${r.bottom - app.top + 6}px`;
    E.menu.style.width = `${w}px`;
    E.menu.style.maxHeight = `${Math.max(160, app.bottom - r.bottom - 16)}px`;
  }
  _menuKey(e) {
    const items = [...this.el.menu.querySelectorAll('[role^="menuitem"]')];
    const i = items.indexOf(document.activeElement);
    let j = null;
    if (e.key === 'ArrowDown') j = (i + 1) % items.length;
    else if (e.key === 'ArrowUp') j = (i - 1 + items.length) % items.length;
    else if (e.key === 'Home') j = 0;
    else if (e.key === 'End') j = items.length - 1;
    else if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); this.closeMenu(true); return; }
    else if (e.key === 'Tab') { this.closeMenu(false); return; }
    else if (/^[1-9]$/.test(e.key) && items[+e.key - 1]) { e.preventDefault(); e.stopPropagation(); items[+e.key - 1].click(); return; }
    if (j == null) { e.stopPropagation(); return; }
    e.preventDefault();
    e.stopPropagation();
    items[j].focus();
  }

  showHint() {
    if (this.hintDismissed) return;
    const coarse = !!(window.matchMedia && matchMedia('(pointer: coarse)').matches);
    this.el.hintText.textContent = coarse
      ? 'Drag to look around · pinch or the arrows to move'
      : 'Drag to look · W A S D or arrows to walk · wheel to move · Esc to exit';
    this.el.hint.hidden = false;
  }

  sync() {
    const t = this.tour, E = this.el, on = t.active;
    E.app.classList.toggle('touring', on);
    E.enter.hidden = on;
    for (const b of [E.exit, E.prev, E.next, E.stop]) b.hidden = !on;
    const s = stopById(t.lastStop);
    E.stopLabel.textContent = s ? s.label : 'Stops';
    E.stop.setAttribute('aria-label', `Interior stop: ${s ? s.label : 'none'}. Choose another stop`);
    for (const b of E.menu.querySelectorAll('[data-stop]')) b.setAttribute('aria-checked', String(on && b.dataset.stop === t.lastStop));
    E.pad.hidden = !on;
    if (!on) E.hint.hidden = true;
    if (!E.menu.hidden) this._place();
    // screen readers: where the camera went
    const say = on ? (s ? `Inside: ${s.label}. ${s.note}.` : 'Inside') : this._said ? 'Back outside' : null;
    if (say && say !== this._said && E.live) E.live.textContent = say;
    this._said = on ? say : null;
  }
}
